# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9TPa-ecKjt_1SOXKpRMr_q2zrnAeb4o
"""

def run_quiz():
    print("WELCOME TO THE PYTHON QUIZ!")

    user_name = input("Please enter your name: ").strip()
    print(f"Hello, {user_name}! Let's test your knowledge with 3 questions.")
    score = 0
    total_questions = 3

    print("Question 1: What is the capital of Srilanka?")
    print("A) moratuwa")
    print("B) negombo")
    print("C) sri jayawardhanapura")
    answer_1 = input("Your answer (A, B, or C): ").strip().lower()

    if answer_1 == "c" or answer_1 == "sri jayawardhanapura":
        print("Correct!")
        score += 1
    else:
        print("Incorrect. The correct answer was C (sri jayawardhanapura).")

    print("Question 2: Who is the president of america?")
    print("A) D.Trump")
    print("B) B.Obama")
    print("C) Jhon Cena")
    answer_2 = input("Your answer (A, B, or C): ").strip().lower()

    if answer_2 == "a" or answer_2 == "D.Trump":
        print("Correct!")
        score += 1
    else:
        print("Incorrect. The correct answer was A (D.Trump).")

    print("Question 3: What is the tallest mountain in the world?")
    print("A) Himalaya")
    print("B) Mount everest")
    print("C) Sigiriya")
    answer_3 = input("Your answer (A, B, or C): ").strip().lower()

    if answer_3 == "b" or answer_3 == "Mount everest":
        print("Correct!")
        score += 1
    else:
        print("Incorrect. The correct answer was B (Mount everest).")

    print(f" QUIZ COMPLETE, {user_name.upper()}! ")

    print(f"Your Final Score: {score} out of {total_questions}")

    if score == total_questions:
        print("Amazing job! You got a perfect score! ")
    elif score > 0:
        print("Good effort! Room for improvement, but well played! ")
    else:
        print("Better luck next time! Keep practicing and try again. ")

if __name__ == "__main__":
    run_quiz()